channels:
- conda-forge
dependencies:
- python=3.7.13
- pip<=20.2.4
- pip:
  - mlflow
  - configparser==3.7.4
  - distributed==2021.10.0
  - ipython==7.34.0
  - lightgbm==3.2.1
  - matplotlib==3.3.4
  - pandas==1.1.5
name: mlflow-env
